version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins_master
    restart: on-failure
    ports:
      - "8080:8080"
      - "50000:50000"
    dns:               # <--- Zid had star
      - 8.8.8.8
    volumes:
      - jenkins_home:/var/jenkins_home
    
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oc_microservices
    restart: on-failure
    ports:
      - "5000:5000"
    dns:
      - 8.8.8.8

volumes:
  jenkins_home: